### ISSUE TITLE
Error on run (windows version of python) 

### ISSUE THREAD

**Issue by foodfan** [philgyford/simplenote-to-obsidian#2]
Hi, I followed the instructions - placed the script, notes.json and .txt files in the same directory, then ran the script, but none of the files were converted. It did create an empty converted notes directory. Here are the errors I got. Any way to fix this? Thanks!

![image](https://user-images.githubusercontent.com/43094559/198859041-caf4bcd2-e91f-4f91-917e-e4bed9a32f4b.png)

**Comment by philgyford** [comment]
Sorry about that. Are you able to narrow it down to a particular note, and part of that note? Looks like it's one or more "unusual" characters in the note.

If you can narrow it down and let me know what's causing the problem I can see if I can fix it. I don't have Windows though, so I might be stuck. Happy to try!

**Comment by higgins720** [comment]
I'm getting a similar error. It appears to be an issue with encoding emojis. 

It worked for me after I added `encoding='UTF-8'` as an argument to the open file methods.

**Comment by philgyford** [comment]
Strange - it worked fine for me (on a Mac) with notes continuing strange UTF-8 characters and emojis.

But I've added `encoding="UTF-8"` now, so hopefully that'll work for more people.
