### ISSUE TITLE
Overwriting existing files

### ISSUE THREAD

**Issue by makulatura** [philgyford/simplenote-to-obsidian#3]
Thank you for your script!

I have tested it with my chaotic simplenote library and I have a suggestion for those that might use it.
The script creates new .md files from first line of note and overwrites existing files without warning. You might suspect that something like this happened if you compare the number of md files that you have in your "notes_converted" directory and the number that the script claims to have created. To make sure that no note is lost I update open parameter from "w" to "x" (line 106):

```
with open(filepath, "x") as outfile:
```

That throws error if script tries to overwrite file. We certainly don't want to overwrite any notes.

I also added these lines ( in line 105) to update filename in case it is about to be overwritten:

```                
                filepath = os.path.join(OUTPUT_DIRECTORY, filename)
                # starting here
                isExist = os.path.exists(filepath)
                
                if isExist is True:
                    print(f"File {filename} exists, generating random one")
                    filename = str(uuid.uuid4()) + ".md"
                    filepath = os.path.join(OUTPUT_DIRECTORY, filename)
                # ending here
                with open(filepath, "x") as outfile:
```

It also happened that some filenames-to-be were longer than my os allowed (255 characters), so I added this length check: (line 101)

``` 
                # Create the new filename/path based on the first line of the note:
                if len(lines[0]) > 252:
                    filename = lines[0][0:252] + ".md"
                else:
                    filename = lines[0] + ".md"   
```

**Comment by philgyford** [comment]
Thanks for this! It *shouldn't* overwrite existing files - by default it creates the `notes_exported` directory to put the new files in. Did you change the value of `OUTPUT_DIRECTORY`?

Good idea about the filename length - I only had short filenames so didn't come across that.

**Comment by makulatura** [comment]
Ok, I didn't make myself clear - the script does not overwrite simplenote archive files, it overwrites freshly created .md file in `OUTPUT_DIRECTORY` if it should create another one with the same name. It happened for me because I had a lot of notes with "Rehearsal" as first line.

**Comment by philgyford** [comment]
Ah, sorry for the misunderstanding! Good point, I hadn't thought of that. I'll add those changes to the script, thank you.

**Comment by philgyford** [comment]
So I added a variation on your ideas:

* It now keeps track of how many times a filename has been used, so that if it comes up again, it can just add a number to the end. So you'd get `my file.md`, `my file 2.md`, `my file 3.md`, etc.
* I trimmed it to 248 characters instead of 252, to take account of potential extra digits added to the end.

Thanks again for reporting this and offering solutions!
